name: selfimprove
channels:
  - conda-forge
dependencies:
  - fastdtw=0.3.4
  - numpy=1.26.4 
  - pip=24.0 
  - python=3.10.13 
  - pip:
      - natsort==8.4.0      
      - pandas==2.2.1
      - scipy==1.12.0
      - sortedcontainers==2.4.0
      - symbolicai==0.6.2
      - tqdm==4.66.2
      - sentence-transformers==2.7.0
